name: Node.js build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [20.x, 22.x, 24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Task
              uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2
            - name: Run check
              run: task check
