name: Node.js build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["**"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                node-version: [20.x, 22.x, 24.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Task
              uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2
            - name: Run check
              run: task check
